/* levels.js — 『あなふさぎのよる』レベルデータ（純データ。ロジック禁止）
 * 記号: # かべ(実は押せる。非wrap面の外周は幾何的に不動) / X おせないかべ /
 *       . 床 / P プレイヤー / B 箱 / G おばけ / O 穴
 * verifyNaive: この知識が無いと解けないことをソルバーで証明するためのルール上書き
 * whisper: 詰まったとき（whisperAfter ターン経過）に出るネコのつぶやき
 */
(function (root, factory) {
  if (typeof module !== 'undefined' && module.exports) module.exports = factory();
  else root.LEVELS = factory();
})(typeof window !== 'undefined' ? window : globalThis, function () {
  'use strict';
  return [
    {
      id: 'n01', time: 'PM 9:00', name: 'いつものよる',
      map: [
        '########',
        '#......#',
        '#.P.B.O#',
        '#......#',
        '########',
      ],
    },
    {
      id: 'n02', time: 'PM 10:00', name: 'まわりみち',
      map: [
        '#########',
        '#...P...#',
        '#...B...#',
        '#...B...#',
        '#.......#',
        '#..O.O..#',
        '#########',
      ],
      whisper: 'かさなった にもつは、いっぺんには おせない。',
      whisperAfter: 25,
    },
    {
      id: 'n03', time: 'PM 11:00', name: 'いきどまり',
      map: [
        '###########',
        '#.B..#....#',
        '#BB..#....#',
        '#.P..#....#',
        '#B...#..O.#',
        '#.B..#....#',
        '###########',
      ],
      verifyNaive: [{ wallPush: false }],
      whisper: 'はこは たくさん あるのに、どれも とどかない。……かべ？',
      whisperAfter: 40,
    },
    {
      id: 'n04', time: 'AM 0:00', name: 'まよなかのおきゃく',
      map: [
        '#########',
        '#P......#',
        '#..#.#..#',
        '#.......#',
        '#..#.#..#',
        '#...G...#',
        '#.......#',
        '#.B....O#',
        '#########',
      ],
      whisper: 'あのこは ついてくるだけで、なにも してこないみたい。',
      whisperAfter: 45,
    },
    {
      id: 'n05', time: 'AM 0:30', name: 'おばけのぎょうれつ',
      map: [
        '##########',
        '#G.G.XXXX#',
        '#G.G.XXXX#',
        '#XXX.XXXX#',
        '#OOO....P#',
        '##########',
      ],
      verifyNaive: [{ ghostPush: false }],
      whisper: 'ひとりは よける。ぎょうれつは にげられない。',
      whisperAfter: 40,
    },
    {
      id: 'n06', time: 'AM 1:00', name: 'じきゅうじそく',
      spawnInterval: 7, ghostCap: 2,
      map: [
        '########',
        '#......#',
        '#.O..O.#',
        '#..XX..#',
        '#.P....#',
        '#......#',
        '########',
      ],
      whisper: 'でてきたところに、もどってもらおう。',
      whisperAfter: 40,
    },
    {
      id: 'n07', time: 'AM 1:30', name: 'わきでるよる',
      spawnInterval: 8, ghostCap: 2,
      map: [
        '#########',
        '#...O...#',
        '#...B...#',
        '#...P...#',
        '#...#...#',
        '#O.....O#',
        '#########',
      ],
      verifyNaive: [{ spawnInterval: 0 }],
      whisper: 'あなは、ふさげば わいてこない。',
      whisperAfter: 50,
    },
    {
      id: 'n08', time: 'AM 2:00', name: 'ぐるりのはて',
      wrap: true,
      map: [
        '................',
        '....X...........',
        '..P....B........',
        '....X.......G...',
        '................',
        'XXXXXXXXXXXXXXXX',
        '......X.........',
        '..........O.....',
        '......X.........',
        '................',
      ],
      verifyNaive: [{ wrap: false }],
      whisper: 'このよるに、はては ないのかも。',
      whisperAfter: 45,
    },
    {
      id: 'n09', time: 'AM 2:30', name: 'おいかけっこ',
      wrap: true,
      map: [
        '....O....',
        '..XXXXX..',
        '......G..',
        '....P....',
        '..XX.XX..',
        '.........',
      ],
      whisper: 'せかいが まるいなら、おいかけっこも まるくなる。',
      whisperAfter: 50,
    },
    {
      id: 'n10', time: 'AM 3:00', name: 'とどかないはこ',
      map: [
        '#########',
        '#.B.....#',
        '#..XXX..#',
        '#.......#',
        '#...O...#',
        '#.......#',
        '#...P...#',
        '#########',
      ],
      verifyNaive: [{ holePush: false }],
      whisper: 'はこが とどかないなら、あなが むかえに いけば いい。',
      whisperAfter: 35,
    },
    {
      id: 'n11', time: 'AM 3:20', name: 'はこがたりない',
      map: [
        '#########',
        '#..O....#',
        '#.B.....#',
        '#P....G.#',
        '#..O....#',
        '#########',
      ],
      verifyNaive: [{ ghostPush: false }],
      whisper: 'はこは 1つ、あなは 2つ。あなのほうを うごかしてもいい。',
      whisperAfter: 30,
    },
    {
      id: 'n12', time: 'AM 3:40', name: 'かべとおばけ',
      verifyNaive: [{ wallPush: false }],
      map: [
        '###########',
        '#....O....#',
        '#....X....#',
        '#.B..X..#.#',
        '#....X....#',
        '#.P..X.G..#',
        '#....X....#',
        '#O.......O#',
        '###########',
      ],
      whisper: 'かべも はこも おばけも、ぜんぶ フタ。',
      whisperAfter: 60,
    },
    {
      id: 'n13', time: 'AM 4:00', name: 'あふれるまえに',
      wrap: true,
      spawnInterval: 6, ghostCap: 3,
      map: [
        'XXXXX.XXXXX',
        'XO........X',
        'X..X..X...X',
        'X..B..P...X',
        'X..X..X...X',
        'XO..B....OX',
        '...........',
        'XXXXX.XXXXX',
      ],
      whisper: 'にげみちは、そとにも ある。',
      whisperAfter: 60,
    },
    {
      id: 'n14', time: 'AM 4:20', name: 'じゅんびのじかん',
      map: [
        '###########',
        '#....X.G..#',
        '#..O.X...G#',
        '#....X..X.#',
        '#.X..X.G..#',
        '#....X...G#',
        '#P...X....#',
        '#OO.......#',
        '###########',
      ],
      verifyNaive: [{ ghostPush: false }],
      whisper: 'さきに あなを ならべておくと、あとが らく。',
      whisperAfter: 60,
    },
    {
      id: 'n15', time: 'AM 4:40', name: 'だいぎょうれつ',
      map: [
        '################',
        '#G.G.G.G.G.XXXX#',
        '#..........XXXX#',
        '#XXXXXXXXX.XXXX#',
        '#OOOO.........P#',
        '################',
      ],
      verifyNaive: [{ ghostPush: false }],
      whisper: 'ごにんも いれば、よんつの あなも こわくない。',
      whisperAfter: 50,
    },
    {
      id: 'n16', time: 'AM 5:00', name: 'おおそうじ',
      map: [
        '#############',
        '#.....X..G..#',
        '#..O..X....G#',
        '#.....X..X..#',
        '#.....X.G...#',
        '#...O.X....G#',
        '#.....X..X..#',
        '#P....X..G..#',
        '#OO.........#',
        '#############',
      ],
      // verifyNaive(ghostPush:false) は敵5体の探索爆発で BFS 不能。
      // ただし本面は箱ゼロ・押せる壁ゼロで栓になり得るのはおばけのみ＝証明は自明。
      whisper: 'ならべて、つれてきて、いっきに おそうじ。',
      whisperAfter: 70,
    },
    {
      id: 'n17', time: 'よあけまえ', name: 'おわかれ',
      spawnInterval: 7, ghostCap: 2,
      map: [
        '#########',
        '#......O#',
        '#.B.X...#',
        '#...X...#',
        '#P..#...#',
        '#..X..X.#',
        '#O.....O#',
        '#########',
      ],
      whisper: 'さいごのフタは……。',
      whisperAfter: 70,
      finale: true,
    },
  ];
});
